# Generated by Django 3.1.7 on 2021-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actor_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_picture',
            field=models.ImageField(height_field='139', upload_to='actorspics', width_field='156'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_cover',
            field=models.ImageField(height_field='139', upload_to='filmcovers', width_field='156'),
        ),
    ]
