# Generated by Django 3.1.7 on 2021-03-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210331_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
    ]
