# Generated by Django 3.1.7 on 2021-03-31 20:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_actor_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[139, 156], upload_to='actorpics'),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[139, 156], upload_to='moviescovers'),
        ),
    ]
