# Generated by Django 3.1.7 on 2021-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_auto_20210331_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_picture',
            field=models.ImageField(blank=True, null=True, upload_to='actorpics'),
        ),
    ]
