# Generated by Django 3.1.7 on 2021-04-02 19:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_auto_20210402_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[139, 156], upload_to='actorpics'),
        ),
    ]
