# Generated by Django 3.1.7 on 2021-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20210331_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, height_field='139', null=True, upload_to='', width_field='156'),
        ),
    ]
