# Generated by Django 3.1.7 on 2021-04-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20210331_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='manager_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_managed_by_me', to='rentals.staff', unique=True),
        ),
    ]
