# Generated by Django 3.1.7 on 2021-04-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20210401_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='manager_staff',
        ),
    ]
