# Generated by Django 3.1.7 on 2021-04-01 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_remove_store_manager_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manager_staff',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_managed_by_me', to='rentals.staff'),
            preserve_default=False,
        ),
    ]
