# Generated by Django 3.1.7 on 2021-04-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_auto_20210401_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_managed_by_me', to='rentals.staff'),
        ),
    ]
