# Generated by Django 3.1.7 on 2021-04-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20210401_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
