# Generated by Django 3.1.7 on 2021-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_auto_20210401_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.IntegerField(),
        ),
    ]
