# Generated by Django 3.1.7 on 2021-04-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_auto_20210401_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='manager_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_managed_by_me', to='rentals.staff'),
        ),
    ]
