# Generated by Django 3.1.7 on 2021-04-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('rentals', '0023_auto_20210401_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.address'),
        ),
    ]
