# Generated by Django 3.1.7 on 2021-04-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0030_auto_20210401_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.RemoveField(
            model_name='store',
            name='manager_staff',
        ),
    ]
