# Generated by Django 3.1.7 on 2021-04-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('rentals', '0032_auto_20210401_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
