# Generated by Django 3.1.7 on 2021-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0033_auto_20210417_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
