# Generated by Django 3.1.7 on 2021-05-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0035_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activebool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
