# Generated by Django 3.1.7 on 2021-05-14 02:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0041_auto_20210513_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='user.png', force_format=None, keep_meta=True, null=True, quality=0, size=[139, 156], upload_to='staffpics'),
        ),
    ]
