# Generated by Django 3.1.7 on 2021-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0043_auto_20210514_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activebool',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
