# Generated by Django 3.1.7 on 2021-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0046_auto_20210515_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='activebool',
            field=models.BooleanField(default=False),
        ),
    ]
